### ISSUE TITLE
Constraint Validation

### ISSUE THREAD

**Issue by jthorton** [openforcefield/qcsubmit#45]
In the recent protein fragment optimization dataset, we used extra constraints which were indexed incorrectly. This may have been caught ahead of runtime by implementing some constraint validation which makes sure the atoms in an angle and dihedral constraint are connected but this would raise errors when users try and add constraints to freeze a hydrogen bond angle or distance. One solution may be to add constraint validation which is run by default but an option to turn it off if the user wants to add these non-connected constraints.  @dotsdl @trevorgokey What do you guys think?

**Comment by trevorgokey** [comment]
I think this type of case where tuples are not bonded justifies a warning. I wouldn't want to search for documentation just to get things to work if QCSubmit decides to error out. We can add a `error_on_nonbonded_constraints=True` or something if we are using it non-interactively. This would prevent mixing bonded and nonbonded constraints, though. So, I am in favor of warnings here.

**Comment by jthorton** [comment]
Yes, good point that would be frustrating for users to make it work I think warnings could work well here and we can check all constraint types.

**Comment by dotsdl** [comment]
All for a check that fails if a constraint is being added on a non-bond, with the ability to switch off in the more exception case that we are freezing non-bonded interactions (like h-bonds).

**Comment by jthorton** [comment]
#48 Should address this as constraints will now raise a warning when the atoms in the constraint are not bonded.
