### ISSUE TITLE
'BasicDatasetFactory' object has no attribute 'basis'

### ISSUE THREAD

**Issue by trevorgokey** [openforcefield/qcsubmit#56]
Using the `conda` version `'0+untagged.222.g3eb3978'`, I get this:

```
import qcsubmit.factories
f = qcsubmit.factories.BasicDatasetFactory()
f.basis

AttributeError              Traceback (most recent call last)
<ipython-input-4-b14ac0026afa> in <module>()
----> 1 f.basis

AttributeError: 'BasicDatasetFactory' object has no attribute 'basis'
```
It appears that there are references to `self.basis` and is in the docstring, but the actual field is absent.

**Comment by dotsdl** [comment]
In the transition to multi-compute-spec support, it looks like the factories have yet to get the same treatment as the dataset classes?

**Comment by jthorton** [comment]
Factories use the same base class as the datasets so they should also support multi compute specs. See [here](https://github.com/openforcefield/qcsubmit/blob/5d1a3303ff2e5313b5b20ebc55333ec30d5e31b3/qcsubmit/factories.py#L32).
