### ISSUE TITLE
Need a way to submit with `overwrite=True`

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/qcsubmit#62]
For reference: https://github.com/openforcefield/qca-dataset-submission/pull/160#issuecomment-732541143

Currently, the `overwrite` keyword for `collection.add_specification` is hardcoded to `False`. For adding specifications that we only partially added, due perhaps to a SIGKILL of the client during submisison, we need a way to overwrite or finish passing in the spec to the collection. 

There may be another approach that is more appropriate that allows for idempotent calls to `dataset.submit()` when a previous call was killed mid-work.

**Comment by jthorton** [comment]
It looks like the call to add the specs worked but the call to compute must have failed. 
I would say there are two possible options here

- the spec was added but no compute was run, this can be checked in ds.data.history
Here we would just overwrite the spec and add it again and run the compute.
- the spec was added and compute has been called on a portion of the dataset
here we would check if the spec is the same as what we are trying to add, if it is not we would throw an error and tell the users a different spec is stored under this name and they should add it again to avoid a db inconsistency that ben mentioned.
